version: '3'

services:
  elasticsearch:
    # 官方推荐镜像，详见https://hub.docker.com/r/library/elasticsearch/
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /Users/undancer/docker-data/srv/docker/es:/usr/share/elasticsearch/data
    networks:
      - stack
    healthcheck:
      test: ['CMD', 'curl', '-f', '-u', 'elastic:changeme', 'http://localhost:9200']
  kibana:
    # 官方推荐镜像，详见https://hub.docker.com/r/library/kibana/
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - stack
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5601/login']
  logstash:
    # 官方推荐镜像，详见https://hub.docker.com/r/library/logstash/
    image: docker.elastic.co/logstash/logstash:$ELASTIC_VERSION
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - stack

# volumes:

networks:
  stack:
