version: '3.6'

services:
  elasticsearch:
    # 官方推荐镜像，详见https://hub.docker.com/r/library/elasticsearch/
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - LOGSPOUT=ignore
    ports:
      - 9200:9200
    networks:
      - esnet
    healthcheck:
      test: ['CMD', 'curl', '-f', '-u', 'elastic:changeme', 'http://localhost:9200']
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: elasticsearch-node1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: elasticsearch-node2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    # 官方推荐镜像，详见https://hub.docker.com/r/library/kibana/
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - LOGSPOUT=ignore
    ports:
      - 5601:5601
    networks:
      - esnet
  logstash:
    # 官方推荐镜像，详见https://hub.docker.com/r/library/logstash/
    image: docker.elastic.co/logstash/logstash:$ELASTIC_VERSION
    container_name: logstash
    environment:
      - LOGSPOUT=ignore
    ports:
      - 5000:5000
      - 5000:5000/udp
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - esnet
  logspout:
    image: gliderlabs/logspout:v3.2.4
    container_name: logspout
volumes:
  esdata:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local
      - stack
  logspout:
    image: gliderlabs/logspout:$LOGSPOUT_VERSION
    environment:
      - LOGSPOUT=ignore
      - DEBUG=true
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - stack
    command: syslog://logstash:5000
    # command: syslog+tcp://logstash:5000


# volumes:

networks:
  esnet:
